// <auto-generated />
using System;
using FlightApp.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FlightApp.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190405125031_create_Airplane")]
    partial class create_Airplane
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FlightApp.Model.Entities.Airplane", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("flightSpeedInKMH");

                    b.Property<double>("fuelConsommationInLiterByFlightSecond");

                    b.Property<string>("name");

                    b.HasKey("Id");

                    b.ToTable("airplanes");
                });

            modelBuilder.Entity("FlightApp.Model.Entities.Airport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("gpsLat");

                    b.Property<double>("gpsLong");

                    b.Property<string>("name");

                    b.HasKey("Id");

                    b.ToTable("airports");
                });

            modelBuilder.Entity("FlightApp.Model.Entities.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("airPlaneId");

                    b.Property<int?>("departureId");

                    b.Property<int?>("destinationId");

                    b.HasKey("Id");

                    b.HasIndex("airPlaneId");

                    b.HasIndex("departureId");

                    b.HasIndex("destinationId");

                    b.ToTable("flights");
                });

            modelBuilder.Entity("FlightApp.Model.Entities.Flight", b =>
                {
                    b.HasOne("FlightApp.Model.Entities.Airplane", "airPlane")
                        .WithMany()
                        .HasForeignKey("airPlaneId");

                    b.HasOne("FlightApp.Model.Entities.Airport", "departure")
                        .WithMany()
                        .HasForeignKey("departureId");

                    b.HasOne("FlightApp.Model.Entities.Airport", "destination")
                        .WithMany()
                        .HasForeignKey("destinationId");
                });
#pragma warning restore 612, 618
        }
    }
}
